name: send email

on:
  schedule:
    - cron: '25 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 
          
        
          
      - name: Install dependencies and send email
      
        env:  
           MAIL_ID: ${{ secrets.MAIL_ID }} 
           PASSWORD: ${{ secrets.PASSWORD }} 
           SHEET_ID: ${{ secrets.SHEET_ID }} 
           API_KEY: ${{ secrets.API_KEY }}
           
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          python src/main.py
